/** User-facing tax invoice PDF copy — keep in sync with FE LABELS where applicable. */
export const TAX_INVOICE_COPY = {
  title: 'GST Tax Invoice',
  invoiceNo: 'Invoice No',
  orderId: 'Order ID',
  invoiceDate: 'Invoice Date',
  payment: 'Payment',
  placeOfSupply: 'Place of Supply / Ship to',
  seller: 'Seller',
  platformSeller: 'Platform',
  gstin: 'GSTIN',
  sellerState: 'Seller state',
  hsn: 'HSN',
  qty: 'Qty',
  taxable: 'Taxable',
  taxableTotal: 'Taxable total',
  grandTotal: 'Grand total',
  walletApplied: 'Wallet applied',
  cgst: 'CGST',
  sgst: 'SGST',
  igst: 'IGST',
  emptyValue: '—',
  currencyPrefix: '₹',
} as const;

/**
 * Excel / API column headers. Keys must match ReportColumn.labelKey and FE LABELS.
 */
export const REPORT_COLUMN_LABELS: Record<string, string> = {
  groupType: 'Group',
  vendorId: 'Vendor ID',
  vendorName: 'Vendor',
  state: 'State',
  period: 'Period',
  taxableValue: 'Taxable Value',
  tcsCgst: 'TCS CGST',
  tcsSgst: 'TCS SGST',
  tcsIgst: 'TCS IGST',
  tcsTotal: 'TCS Total',
  section: 'Section',
  grossTaxable: 'Gross Taxable',
  tdsAmount: 'TDS Amount',
  hsnCode: 'HSN Code',
  qty: 'Quantity',
  taxable: 'Taxable',
  tax: 'Tax',
  cgst: 'CGST',
  sgst: 'SGST',
  igst: 'IGST',
  taxTotal: 'Tax Total',
  customerPayments: 'Customer Payments',
  vendorNetPayouts: 'Vendor Net Payouts',
  platformCommission: 'Platform Commission',
  taxCollected: 'Tax Collected',
  tcsCollected: 'TCS Collected',
  shippingCollected: 'Shipping Collected',
  refundsToCustomer: 'Refunds To Customer',
  accountedTotal: 'Accounted Total',
  difference: 'Difference',
  status: 'Status',
  type: 'Type',
  noteNumber: 'Note Number',
  orderId: 'Order ID',
  amount: 'Amount',
  taxAmount: 'Tax Amount',
  reason: 'Reason',
  issuedAt: 'Issued At',
  pendingNet: 'Pending Net',
  settledNet: 'Settled Net',
  payoutAmount: 'Payout Amount',
  payoutPending: 'Payout Pending',
  payoutPaid: 'Payout Paid',
  payoutStatus: 'Payout Status',
  categoryId: 'Category ID',
  commission: 'Commission',
  discountBearer: 'Discount Bearer',
  discountAmount: 'Discount Amount',
  gmv: 'GMV',
  createdAt: 'Created At',
  actorId: 'Actor ID',
  action: 'Action',
  entityType: 'Entity Type',
  entityId: 'Entity ID',
  metadata: 'Metadata',
  subOrderId: 'Sub-order ID',
  deliveredAt: 'Delivered At',
  hoursToDeliver: 'Hours to Deliver',
  level: 'Level',
  cancelledAt: 'Cancelled At',
  id: 'Return ID',
  orderItemId: 'Order Item ID',
  reasonCode: 'Reason Code',
  refundStatus: 'Refund Status',
  refundAmount: 'Refund Amount',
  turnaroundHours: 'Turnaround Hours',
  resolvedAt: 'Resolved At',
  productId: 'Product ID',
  productName: 'Product',
  categoryName: 'Category',
  revenue: 'Revenue',
  submittedAt: 'Submitted At',
  decidedAt: 'Decided At',
  approvedById: 'Approved By',
  reviewCount: 'Reviews',
  avgRating: 'Avg Rating',
  approvedCount: 'Approved',
  pendingCount: 'Pending',
  rejectedCount: 'Rejected',
  subtotal: 'Subtotal',
  netPayout: 'Net Payout',
  invoiceId: 'Invoice',
  payoutId: 'Payout ID',
  periodStart: 'Period Start',
  periodEnd: 'Period End',
  paidAt: 'Paid At',
  razorpayPayoutId: 'Razorpay Payout ID',
  saleAmount: 'Sale Amount',
  commissionRate: 'Commission Rate',
  commissionAmount: 'Commission Amount',
  tcsAmount: 'TCS Amount',
  sku: 'SKU',
  stock: 'Stock',
  lowStockAt: 'Low Stock At',
  isLowStock: 'Low Stock',
  price: 'Price',
  valuation: 'Valuation',
  updatedAt: 'Updated At',
  orderStatus: 'Order Status',
  subOrderStatus: 'Sub-order Status',
  quantity: 'Qty',
  paymentStatus: 'Payment Status',
  totalAmount: 'Total',
  discountTotal: 'Discount',
  subOrderCount: 'Sub-orders',
  variantId: 'Variant ID',
};

export function resolveReportColumnLabel(labelKey: string): string {
  return REPORT_COLUMN_LABELS[labelKey] ?? labelKey;
}
