/** User-facing tax invoice PDF copy — keep in sync with FE LABELS where applicable. */
export const TAX_INVOICE_COPY = {
  title: 'GST Tax Invoice',
  originalForRecipient: 'Original for Recipient',
  continuation: 'Continued',
  invoiceNo: 'Invoice No',
  orderId: 'Order ID',
  invoiceDate: 'Invoice Date',
  payment: 'Payment',
  billTo: 'Bill To',
  placeOfSupply: 'Place of supply',
  seller: 'Sold by',
  platformSeller: 'Platform',
  gstin: 'GSTIN',
  sellerState: 'State',
  description: 'Description',
  hsn: 'HSN',
  qty: 'Qty',
  taxable: 'Taxable',
  discount: 'Disc.',
  gstRate: 'GST %',
  amount: 'Amount',
  taxableTotal: 'Taxable total',
  taxTotal: 'Tax total',
  grandTotal: 'Grand total',
  invoiceValue: 'Invoice value',
  platformContribution: 'Less: coupon paid by the platform (incl. GST)',
  walletApplied: 'Wallet applied',
  onlinePaid: 'Online / Razorpay',
  cashOnDelivery: 'Cash on delivery',
  amountInWords: 'Amount in words',
  cgst: 'CGST',
  sgst: 'SGST',
  igst: 'IGST',
  emptyValue: '--',
  currencyPrefix: 'Rs ',
  computerGenerated:
    'This is a computer-generated tax invoice and does not require a signature.',
  paymentMethodLabels: {
    RAZORPAY: 'Razorpay',
    COD: 'Cash on delivery',
    WALLET: 'Wallet',
    WALLET_PLUS_RAZORPAY: 'Wallet + Razorpay',
    WALLET_PLUS_COD: 'Wallet + Cash on delivery',
  } as Record<string, string>,
  paymentStatusLabels: {
    PENDING: 'Pending',
    PAID: 'Paid',
    FAILED: 'Failed',
    REFUNDED: 'Refunded',
  } as Record<string, string>,
} as const;

/**
 * Excel / API column headers. Keys must match ReportColumn.labelKey and FE LABELS.
 */
export const REPORT_COLUMN_LABELS: Record<string, string> = {
  groupType: 'Group',
  vendorId: 'Vendor ID',
  vendorName: 'Vendor',
  vendorGstin: 'Vendor GSTIN',
  state: 'State',
  period: 'Period',
  taxableValue: 'Taxable Value',
  tcsCgst: 'TCS CGST',
  tcsSgst: 'TCS SGST',
  tcsIgst: 'TCS IGST',
  tcsTotal: 'TCS Total',
  section: 'Section',
  entryType: 'Entry Type',
  placeOfSupplyState: 'Place of Supply',
  againstInvoiceNumber: 'Against Invoice',
  subOrderId: 'Sub-order ID',
  grossTaxable: 'Gross Taxable',
  tdsAmount: 'TDS Amount',
  agentName: 'Agent',
  pan: 'PAN',
  quarter: 'Quarter',
  agentPayoutGross: 'Gross Earnings',
  agentPayoutNet: 'Net Paid',
  tdsRatePercent: 'TDS %',
  payoutGross: 'Sales Net',
  commissionGst: 'GST on Commission',
  payoutAdjustments: 'Adjustments',
  hsnCode: 'HSN Code',
  qty: 'Quantity',
  taxable: 'Taxable',
  tax: 'Tax',
  cgst: 'CGST',
  sgst: 'SGST',
  igst: 'IGST',
  taxTotal: 'Tax Total',
  customerPayments: 'Customer Payments',
  vendorNetPayouts: 'Vendor Net Payouts',
  platformCommission: 'Platform Commission',
  taxCollected: 'Tax Collected',
  tcsCollected: 'TCS Collected',
  shippingCollected: 'Shipping Collected',
  refundsToCustomer: 'Refunds To Customer',
  platformFundedDiscount: 'Platform-funded Coupons',
  platformGoodsSales: 'Platform Goods Sales',
  shippingRefunded: 'Shipping Refunded',
  returnFeesKept: 'Return Fees Kept',
  giftWrapCollected: 'Gift Wrap Collected',
  accountedTotal: 'Accounted Total',
  difference: 'Difference',
  status: 'Status',
  type: 'Type',
  noteNumber: 'Note Number',
  orderId: 'Order ID',
  amount: 'Amount',
  taxAmount: 'Tax Amount',
  reason: 'Reason',
  issuedAt: 'Issued At',
  pendingNet: 'Pending Payable',
  settledNet: 'Settled Payable',
  payoutFailed: 'Payout Failed',
  payoutAmount: 'Payout Amount',
  payoutPending: 'Payout Pending',
  payoutPaid: 'Payout Paid',
  payoutStatus: 'Payout Status',
  categoryId: 'Category ID',
  commission: 'Commission',
  discountBearer: 'Discount Bearer',
  discountAmount: 'Discount (excl. GST)',
  vendorDiscount: 'Vendor-funded discount (excl. GST)',
  platformDiscount: 'Platform-funded discount (excl. GST)',
  platformDiscountGst: 'GST on platform-funded discount',
  freeShippingCost: 'Free-shipping cost',
  platformCouponCost: 'Platform coupon cost',
  gmv: 'GMV (before discounts, excl. GST)',
  netSales: 'Net sales (after discounts, excl. GST)',
  createdAt: 'Created At',
  actorId: 'Actor ID',
  action: 'Action',
  entityType: 'Entity Type',
  entityId: 'Entity ID',
  metadata: 'Metadata',
  deliveredAt: 'Delivered At',
  hoursToDeliver: 'Hours to Deliver',
  level: 'Level',
  couponSavings: 'Coupon savings (incl. GST)',
  cancelledAmount: 'Amount cancelled (incl. GST and shipping)',
  cancelledAt: 'Cancelled At',
  id: 'Return ID',
  orderItemId: 'Order Item ID',
  reasonCode: 'Reason Code',
  refundStatus: 'Refund Status',
  refundAmount: 'Refund Amount',
  turnaroundHours: 'Turnaround Hours',
  resolvedAt: 'Resolved At',
  productId: 'Product ID',
  productName: 'Product',
  categoryName: 'Category',
  revenue: 'Revenue',
  submittedAt: 'Submitted At',
  decidedAt: 'Decided At',
  approvedById: 'Approved By',
  reviewCount: 'Reviews',
  avgRating: 'Avg Rating',
  approvedCount: 'Approved',
  pendingCount: 'Pending',
  rejectedCount: 'Rejected',
  subtotal: 'Subtotal',
  netPayout: 'Net Payout',
  invoiceId: 'Invoice',
  payoutId: 'Payout ID',
  periodStart: 'Period Start',
  periodEnd: 'Period End',
  paidAt: 'Paid At',
  paymentReferenceNumber: 'Payment Reference Number',
  saleAmount: 'Sale Amount',
  commissionRate: 'Commission Rate',
  commissionAmount: 'Commission Amount',
  tcsAmount: 'TCS Amount',
  sku: 'SKU',
  stock: 'Stock',
  lowStockAt: 'Low Stock At',
  isLowStock: 'Low Stock',
  price: 'Price',
  valuation: 'Valuation',
  updatedAt: 'Updated At',
  orderStatus: 'Order Status',
  subOrderStatus: 'Sub-order Status',
  quantity: 'Qty',
  paymentStatus: 'Payment Status',
  totalAmount: 'Total',
  discountTotal: 'Discount',
  subOrderCount: 'Sub-orders',
  variantId: 'Variant ID',
  taxInvoiceNumber: 'Tax Invoice No',
  taxInvoiceIssuedAt: 'Tax Invoice Date',
  buyerGstin: 'Buyer GSTIN',
  buyerName: 'Buyer Name',
  documentNumber: 'Document No',
  supplierName: 'Supplier',
  supplierGstin: 'Supplier GSTIN',
  gstRate: 'GST %',
  docType: 'Document',
  documentDate: 'Document Date',
  recipientGstin: 'Recipient GSTIN',
  line: 'Line',
  paymentMethod: 'Payment Method',
  razorpayOrderId: 'Razorpay Order ID',
  razorpayPaymentId: 'Razorpay Payment ID',
  razorpayAmount: 'Razorpay Amount',
  pgSourceType: 'Payment For',
  giftCardCount: 'Cards',
  pgReferenceId: 'Reference ID',
  pgCaptured: 'Captured',
  pgRefunded: 'Refunded',
  pgNet: 'Net Captured',
  walletUsed: 'Wallet Used',
  reconStatus: 'Reconciliation Status',
  codAmount: 'COD Amount',
  codCollected: 'COD Collected',
  codStatus: 'COD Status',
  userId: 'User ID',
  email: 'Email',
  name: 'Name',
  orderCount: 'Order Count',
  totalSpent: 'Total Spent',
  firstOrderAt: 'First Order',
  lastOrderAt: 'Last Order',
  segment: 'Segment',
  shippingCost: 'Shipping Cost',
  shippingCharged: 'Shipping Charged',
  carrier: 'Carrier',
  shipmentStatus: 'Shipment Status',
  shippedAt: 'Shipped At',
  cartId: 'Cart ID',
  lastActivityAt: 'Last Activity',
  itemCount: 'Item Count',
  cartValue: "Cart value (incl. GST, today's prices)",
  ticketNumber: 'Ticket No',
  category: 'Category',
  priority: 'Priority',
  firstResponseAt: 'First Response',
  firstResponseHours: 'First Response (hrs)',
  resolutionHours: 'Resolution (hrs)',
  verifiedDocs: 'Verified Docs',
  pendingDocs: 'Pending Docs',
  rejectedDocs: 'Rejected Docs',
  complianceStatus: 'Compliance Status',
  balanceAfter: 'Balance After',
  referenceType: 'Reference Type',
  referenceId: 'Reference ID',
  description: 'Description',
  metric: 'Metric',
  value: 'Value',
  subscribedAt: 'Subscribed At',
  purchasedPoints: 'Purchased Points',
  promotionalPoints: 'Promotional Points',
  pointSource: 'Point Source',
  pointsAmount: 'Points',
  pointsBalanceAfter: 'Balance (Points)',
  pointsCredited: 'Points Credited',
  amountInr: 'Amount (INR)',
  walletRechargeInflow: 'Wallet Recharge Inflow',
  giftCardRedemptionInflow: 'Gift Card Redemptions',
  walletPointsRedeemedAtCheckout: 'Wallet Points Redeemed',
};

export function resolveReportColumnLabel(labelKey: string): string {
  return REPORT_COLUMN_LABELS[labelKey] ?? labelKey;
}
