/** Machine-readable API error codes (response `error.code`). */
export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_REQUIRED: 'REFRESH_REQUIRED',
  SESSION_REQUIRED: 'SESSION_REQUIRED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  CONFIG_ERROR: 'CONFIG_ERROR',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  RAZORPAY_NOT_CONFIGURED: 'RAZORPAY_NOT_CONFIGURED',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  ITEMS_UNAVAILABLE: 'ITEMS_UNAVAILABLE',
  VENDOR_UNAVAILABLE: 'VENDOR_UNAVAILABLE',
  COUPON_INACTIVE: 'COUPON_INACTIVE',
  COUPON_INVALID: 'COUPON_INVALID',
  COUPON_NOT_APPLICABLE: 'COUPON_NOT_APPLICABLE',
  COUPON_SCOPE: 'COUPON_SCOPE',
  COUPON_RESTRICTION: 'COUPON_RESTRICTION',
  COUPON_MIN_ORDER: 'COUPON_MIN_ORDER',
  COUPON_STACK: 'COUPON_STACK',
  COUPON_PRIORITY: 'COUPON_PRIORITY',
  COUPON_CONFIG_INVALID: 'COUPON_CONFIG_INVALID',
  COUPON_DUPLICATE_SCOPE: 'COUPON_DUPLICATE_SCOPE',
  DOCUMENT_SEQUENCE_MISSING: 'DOCUMENT_SEQUENCE_MISSING',
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_INVALID_AMOUNT: 'WALLET_INVALID_AMOUNT',
  RETURN_INVALID_TRANSITION: 'RETURN_INVALID_TRANSITION',
  RETURN_NOT_RECEIVED: 'RETURN_NOT_RECEIVED',
  RETURN_REFUND_PENDING: 'RETURN_REFUND_PENDING',
  ITEM_MUST_BE_DELIVERED: 'ITEM_MUST_BE_DELIVERED',
  RETURN_ALREADY_EXISTS: 'RETURN_ALREADY_EXISTS',
  VENDOR_NOT_LINKED: 'VENDOR_NOT_LINKED',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_FORBIDDEN: 'REPORT_FORBIDDEN',
  REPORT_EXPORT_NOT_READY: 'REPORT_EXPORT_NOT_READY',
  S3_NOT_CONFIGURED: 'S3_NOT_CONFIGURED',
  S3_ACCESS_DENIED: 'S3_ACCESS_DENIED',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  UPLOAD_FORBIDDEN: 'UPLOAD_FORBIDDEN',
  VENDOR_KYC_INCOMPLETE: 'VENDOR_KYC_INCOMPLETE',
  VENDOR_KYC_BLOCKS_PRODUCT: 'VENDOR_KYC_BLOCKS_PRODUCT',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** Repeated error messages (2+ call sites). One-off messages stay inline. */
export const ERROR_MESSAGES = {
  FORBIDDEN: 'You do not have permission to perform this action',
  NOT_FOUND: 'Not found',
  INSUFFICIENT_STOCK: 'Insufficient stock',
  COUPON_USAGE_LIMIT: 'Coupon usage limit reached',
  COUPON_PRIORITY: 'A higher-priority coupon is already applied',
  COUPON_CONFIG_INVALID: 'Coupon configuration is incomplete for this type',
  CART_EMPTY: 'Cart is empty',
  AUTH_REQUIRED: 'Authentication required',
  INVALID_TOKEN: 'Invalid token',
  TOKEN_EXPIRED: 'Token expired',
  USER_NOT_FOUND_OR_BLOCKED: 'User not found or blocked',
  REFRESH_REQUIRED: 'Refresh token required',
  SESSION_REQUIRED: 'Current session cookie required',
  INTERNAL_ERROR: 'Something went wrong',
  RATE_LIMITED: 'Too many requests, please try again later.',
  NOT_YOUR_ORDER: 'Not your order',
  NO_ACCESS_TO_ORDER: 'You do not have access to this order',
  RAZORPAY_NOT_CONFIGURED: 'Razorpay is not configured',
  NOT_YOUR_PRODUCT: 'Not your product',
  INVALID_CREDENTIALS: 'Invalid credentials',
  EMAIL_ALREADY_REGISTERED: 'Email already registered',
  ACCOUNT_BLOCKED: 'Account is blocked',
  VENDOR_NOT_PENDING: 'Vendor is not in PENDING status',
  VENDOR_KYC_INCOMPLETE:
    'Vendor cannot be approved until all required KYC documents are uploaded and verified',
  VENDOR_KYC_BLOCKS_PRODUCT:
    'This category requires additional verified KYC documents before the product can go live',
  VENDOR_BUSINESS_NAME_EXISTS: 'Business name already exists',
  VENDOR_CATEGORIES_INVALID: 'One or more categories are invalid',
  VENDOR_ENTITY_TYPE_REQUIRED: 'Business entity type is required',
  PRODUCT_NAME_EXISTS: 'Product name already exists',
  PRODUCT_NOT_DRAFT: 'Product is not in DRAFT status',
  PRODUCT_NOT_PENDING_APPROVAL: 'Product is not pending approval',
  CATEGORY_NAME_EXISTS: 'Category name already exists',
  CATEGORY_HAS_SUBCATEGORIES: 'Cannot delete category with subcategories',
  CATEGORY_HAS_PRODUCTS: 'Cannot delete category while products still use it',
  CATEGORY_INVALID_PARENT: 'Category cannot be its own parent or descendant',
  CATEGORY_MAX_DEPTH: 'Categories support at most 3 levels (Department → Category → Subcategory)',
  CATEGORY_INACTIVE: 'Category must be active to assign products',
  CATEGORY_REASSIGN_SAME: 'Source and target categories must be different',
  CATEGORY_ATTRIBUTE_EXISTS: 'An attribute with this name already exists on the category',
  CATEGORY_SECONDARY_INVALID:
    'Secondary categories must be active and different from the primary category',
  ITEMS_UNAVAILABLE: 'Some items in your cart are no longer available',
  VENDOR_UNAVAILABLE: 'This seller is currently unavailable',
  COUPON_INACTIVE: 'Coupon is not active',
  COUPON_INVALID: 'Coupon is invalid or expired',
  COUPON_NOT_APPLICABLE: 'Coupon is not applicable to this cart',
  COUPON_SCOPE: 'Coupon does not apply to items in your cart',
  COUPON_RESTRICTION: 'You are not eligible for this coupon',
  COUPON_MIN_ORDER: 'Order does not meet the minimum requirements for this coupon',
  COUPON_STACK: 'This coupon cannot be combined with another coupon',
  COUPON_DUPLICATE_SCOPE:
    'Only one platform coupon and one coupon per seller can be applied together',
  DOCUMENT_SEQUENCE_MISSING: 'Document number sequence is not configured',
  WALLET_INSUFFICIENT_BALANCE: 'Insufficient wallet balance',
  WALLET_INVALID_AMOUNT: 'Wallet amount must be greater than zero',
  RETURN_INVALID_TRANSITION: 'This return status transition is not allowed',
  RETURN_NOT_RECEIVED: 'Return must be received before it can be closed',
  RETURN_REFUND_PENDING: 'Refund must complete before this action',
  RETURN_WINDOW_EXPIRED: 'The return window for this item has expired',
  ITEM_MUST_BE_DELIVERED: 'Item must be delivered before requesting a return',
  RETURN_ALREADY_EXISTS: 'A return already exists for this item',
  VENDOR_NOT_LINKED: 'No vendor profile is linked to this account',
  SHOP_UNAVAILABLE: 'This shop is currently unavailable',
  NOT_YOUR_VENDOR_REPORT: 'Not your vendor report',
  REPORT_INVALID_RANGE: 'Report date range is invalid',
  REPORT_RECONCILIATION_MISMATCH: 'Settlement reconciliation does not balance for the selected period',
  REPORT_NOT_FOUND: 'Report type not found',
  REPORT_FORBIDDEN: 'You do not have access to this report',
  REPORT_EXPORT_NOT_READY: 'Report export is not ready yet',
  S3_NOT_CONFIGURED:
    'File upload is not available right now. Please try again later.',
  S3_ACCESS_DENIED:
    'File upload is temporarily unavailable. Please try again later or contact support.',
  UPLOAD_INVALID_DATA_URL: 'Invalid file data URL',
  UPLOAD_INVALID_CONTENT_TYPE: 'File type is not allowed for this upload',
  UPLOAD_EMPTY: 'File is empty',
  UPLOAD_TOO_LARGE: 'File must be under 5MB',
  UPLOAD_INVALID_PURPOSE: 'Upload purpose is not valid for this entity type',
  UPLOAD_FAILED: 'File upload failed',
  UPLOAD_FORBIDDEN: 'You do not have permission to upload for this entity',
} as const;
